---
abstract: 'Adds LastTransactionContent as a search display column'
author:
  - 'Best Practical Solutions.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-TicketlistTransactions
no_index:
  directory:
    - html
    - inc
version: 0.01
